aliases: {soc: Qick233}
device:
  qubit:
    T1: [41.03, 22.31, 19.81, 4.86, 13.24, 1.5, 16.65, 9.16, 2.14, 7.08, 7.08, 22.61,
      29.63, 16.32, 16.24, 22.11, 8.58, 31.94, 13.79, 20.23]
    T2e: [22.11, 44.67, 33.55, 8.41, 13.2, 1.5, 30.22, 4.93, 4.1, 14.19, 13.02, 31.73,
      45.23, 3.84, 34.42, 42.33, 10.54, 59.25, 25.16, 37.74]
    T2r: [19.58, 31.28, 29.07, 6.66, 9.83, 7.53, 8.09, 18.42, 1.52, 12.29, 1.39, 4.73,
      32.7, 3.73, 11.12, 9.95, 11.22, 37.66, 8.34, 23.38]
    f_ef: [4099.4495, 4482.9871, 4666.2227, 4865.8348, 5079.66, 5314.21, 5827.7102,
      5853.2962, 6218.2587, 6449.0591, 4151.8963, 4318.0058, 4645.2807, 4836.7823,
      5098.7575, 5292.7146, 5712.7437, 6072.8284, 5997.3919, 6300.8536]
    f_ge: [4273.0621, 4637.7492, 4784.9022, 5028.7995, 5188.9961, 5423.9551, 5793.4332,
      5946.2873, 6291.9677, 6391.9667, 4341.3423, 4528.2133, 4767.8287, 6567.079,
      5255.7469, 5469.5476, 5692.4964, 6057.257, 6158.9878, 6481.3042]
    kappa: [-2.4011, 8.9645, 89.5136, 2.8525, 4.9926, 34.5271, -1.9496, 4.2424, -2.9552,
      0.0879, 0.3588, 1.1029, 0, 0.3281, 0, 0, 0, 0, 0, 0]
    low_gain: 0.002
    max_gain: 1
    pop: [0.0008, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0007, 0.0017, 0.0011, 0, 0, 0, 0, 0,
      0, 0]
    pulses:
      pi_ef:
        gain: [0.3662, 0.0886, 0.0935, 0.0532, 0.1051, 0.15, 0.2196, 0.0874, 0.1105,
          0.15, 0.0072, 0.0132, 0.0089, 0.097, 0.128, 0.1135, 0.1201, 0.3665, 0.1835,
          0.2107]
        sigma: [0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
          0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss,
          gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.271, 0.226, 0.2041, 0.1297, 0.202, 0.1126, 0.3333, 0.195, 0.1908,
          0.2397, 0.0539, 0.0346, 0.0331, 0.6565, 0.0247, 0.0338, 0.0324, 0.0613,
          0.0391, 0.0372]
        sigma: [0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07,
          0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07]
        sigma_inc: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss,
          gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1, 2, 10, 2, 2, 2, 2, 0.1, 0.1, 0.1, 0.8, 0.1, 0.1, 0.2,
      0.2, 0.4, 0.1]
    temp: [28.9479, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28.915, 33.9275, 33.9044, 0, 0, 0,
      0, 0, 0, 0]
    tuned_up: [true, true, true, true, true, false, true, true, true, true, true,
      true, true, true, true, true, true, true, true, true]
  readout:
    active_reset: [false, false, false, false, false, false, false, false, false,
      false, false, false, false, false, false, false, false, false, false, false]
    chi: [-1.438, -1.6441, -1.5972, -1.7851, -1.7381, 0.9395, -2.1139, -2.1139, -1.1274,
      2.2078, -1.5032, -1.5032, 0.7986, -1.6911, -2.2078, -1.5502, -0.6107, -2.5367,
      -1.973, -2.8761]
    fidelity: [0.8247, 0.8096, 0.7828, 0.5515, 0.1516, 0.0391, 0.5506, 0.4131, 0.128,
      0.2553, 0.6578, 0.4269, 0.5964, 0.5667, 0.6599, 0.7824, 0.3604, 0.5955, 0.4924,
      0.5838]
    final_delay: [246.16, 133.85, 118.84, 29.15, 79.43, 10, 99.91, 54.95, 12.86, 42.46,
      42.45, 135.68, 177.8, 97.91, 97.46, 132.64, 51.48, 191.65, 82.76, 121.36]
    frequency: [1390.8844, 1668.0312, 1825.2599, 1975.3867, 2213.1722, 2492.6353,
      2565.3661, 2790.1102, 3161.0239, 3212.3607, 1700.0244, 1113.5174, 1418.5513,
      1566.2535, 1806.4016, 2085.4369, 2155.7843, 1885.0258, 2588.2152, 2256.1272]
    gain: [0.4015, 0.498, 0.4792, 0.4355, 0.3155, 0.8504, 0.6926, 1.0, 0.5258, 1.0,
      0.2076, 0.1219, 0.1071, 0.3256, 0.1203, 0.1664, 0.3082, 0.1973, 0.1788, 0.4493]
    ie: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ig: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    kappa: [0.6091, 0.6307, 0.4503, 0.3801, 0.2869, 0.5612, 0.2183, 0.2663, 0.5038,
      0.3608, 0.3101, 0.55, 0.1188, 0.4156, 0.1981, 0.247, 0.5554, 0.1884, 0.3527,
      0.2011]
    lamb: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    max_gain: 1
    phase: [164.3442, 107.2131, 128.963, -123.4281, -149.4357, -168.446, -64.6001,
      -19.8544, 175.6572, 65.1311, 45.7797, -102.7411, -141.0909, 119.8797, 124.0563,
      -58.9157, 86.1998, -151.8966, 132.3871, 93.7174]
    qe: [3.1888, 5.5194, 2.5946, 4.3062, 4.401, 3.4925, 5.8334, 9.4346, 3.4358, 12.2832,
      3.0277, 2.2969, 9.7435, 18.5853, 10.7203, 10.3536, 8.3229, 3.2588, 7.0546, 51.3737]
    qi: [1.4222, 1.2121, 3.1703, 2.8909, 5.1577, 1.9806, 7.5086, 3.9311, 2.7928, 2.3764,
      5.4799, 5.0269, 9.2411, 1.7268, 4.9305, 4.0792, 0.9835, 0.9641, 3.1612, 4.17]
    readout_length: [5.7845, 3.7022, 2.5961, 2.7755, 4.217, 1.7105, 10.3182, 9.5695,
      2.1142, 7.2892, 5.321, 4.2823, 12.4597, 6.4444, 5.4696, 8.1424, 6.5732, 3.4754,
      2.8898, 9.7362]
    reps: [1.2477, 1.2814, 1.5781, 2.1315, 1.8724, 9.4915, 4.9772, 9.5316, 15, 7.6218,
      1.5907, 1.5988, 2.6294, 15.0912, 1.9176, 1.413, 14.8305, 2.7062, 2.9133, 2.5903]
    reps_base: 200
    reset_e: [0.0641, 0.0426, 0.0148, 0.4379, 0.1493, 0.0409, 0.1953, 0.9035, 1.0953,
      0.0442, 0.1727, 0.0553, 0.7494, 0.8039, 1.005, 0.1317, 0.6374, 0.6964, 2.5606,
      0.3751]
    reset_g: [9.44, 4.2698, 1.7893, 0.8918, 0.7604, 1.4943, 1.5224, 0.8657, 1.3004,
      0.1508, 14.8792, 4.5578, 2.38, 6.6277, 0.6775, 0.173, 4.3562, 0.7638, 0.6843,
      0.4741]
    sigma: [2.3675, 4.1315, 3.9756, 3.4683, 2.4319, 3.8673, 2.5179, 1.3735, 4.0231,
      2.7586, 3.1558, 2.8595, 1.8414, 2.5673, 2.0215, 1.5556, 6.0848, 2.3276, 2.4995,
      0.9801]
    soft_avgs: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    soft_avgs_base: 1
    threshold: [6.2158, 20.1602, 18.453, 17.5831, 9.6086, -0.914, 13.2752, 6.618,
      7.8969, 8.6393, 10.0193, 8.5824, 6.9307, 22.7654, 10.7525, 8.0793, 4.3729, 11.2976,
      8.8184, 15.0477]
    tm: [0.2382, 0.1179, 0.1997, 0.4437, 0.4388, 0.3346, -0.0, 0.9823, 1.481, 1.0525,
      0.4601, 0.4539, 0.5592, -0.0049, 0.2795, 0.3471, -0.143, 0.0651, 0.425, 0.7837]
    trig_offset: [0.506, 0.506, 0.506, 0.506, 0.506, 0.506, 0.506, 0.506, 0.506, 0.506,
      0.526, 0.526, 0.526, 0.526, 0.526, 0.526, 0.526, 0.526, 0.526, 0.526]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    dacs:
      qubit:
        ch: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        nyquist: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
        type: [full, full, full, full, full, full, full, full, full, full, full, full,
          full, full, full, full, full, full, full, full]
      readout:
        ch: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
        lo_freq: [4600, 4600, 4600, 4600, 4600, 4600, 4600, 4600, 4600, 4600, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0]
        nyquist: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
        type: [full, full, full, full, full, full, full, full, full, full, full, full,
          full, full, full, full, full, full, full, full]
    lo:
      ch: [None, None, None, None, None, None, None, None, None, None, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5]
      gain: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      mixer_freq: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5000, 5150, 5000, 5000, 5000, 5000,
        5000, 5500, 5000, 5500]
      nyquist: [None, None, None, None, None, None, None, None, None, None, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2]
stark:
  l: [156.5944, 879.7441, 370.4449, -0.3188, 0.5836, -1403.8115, 8.2019, 15.896, 3.4444,
    -1990.7803, 31.9059, -8.1716, 1999.5065, -6.1496, -51.0763, 0.2487, -7.4557, -1.5186,
    34.5347, 8.0786]
  lneg: [19.4142, 53.0068, 5.7696, 6.5911, 4.5831, 277.6781, 83.1711, 6.4863, 194.2645,
    -2.9311, 135.4532, -6.7555, -42.4482, -2.1739, -992.8835, -4.2142, 0.0623, 17.2018,
    -0.618, -36.5908]
  o: [88.3159, -66.7723, -8.5749, 0.4134, 0.0434, 46.3301, -0.4578, -0.1803, 1.2162,
    70.7398, -4.7875, 0.8714, -99.7129, 1.535, -0.9821, 0.4149, 0.6135, 2.1839, -1.7694,
    -0.677]
  oneg: [-0.6491, -0.4491, -0.795, -1.1334, -0.8914, -49.1727, -3.9101, -1.1195, -7.7521,
    0.3606, -3.6496, 2.0622, 11.5879, 0.3077, 119.2631, 1.0815, -0.1649, -2.9076,
    0.1716, 13.7161]
  q: [-192.6166, -20.0601, -536.7374, 10.5383, 6.7144, 11169.716, 117.1865, 0.5988,
    453.4503, 12837.8909, 2.5753, 77.3266, -5386.7697, 111.8167, 331.8952, 1.8571,
    45.6312, -1.3124, -52.6454, 20.1213]
  qneg: [987.3256, 1123.2648, 15.3499, 20.2056, 8.2615, -164.6363, 253.6482, 9.7711,
    250.2605, 12.7884, 992.5259, 11.0876, 53.5874, 9.6044, 2667.2861, 10.0006, 7.815,
    -6.0679, 5.5261, 1290.4576]
