aliases: {soc: bf1_soc}
device:
  qubit:
    T1: [30, 30, 30, 30, 30, 30, 30, 30]
    T2e: [60, 60, 60, 60, 60, 60, 60, 60]
    T2r: [30, 30, 30, 30, 30, 30, 30, 30]
    f_ef: [3800, 3800, 3800, 3800, 3800, 3800, 3800, 3800]
    f_ge: [4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000]
    kappa: [0, 0, 0, 0, 0, 0, 0, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0, 0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
        sigma: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5, 5, 5, 5, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
        sigma: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5, 5, 5, 5, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1, 1, 1, 1, 1]
    temp: [0, 0, 0, 0, 0, 0, 0, 0]
    tuned_up: [false, false, false, false, false, false, false, false]
  readout:
    active_reset: [false, false, false, false, false, false, false, false]
    chi: [0, 0, 0, 0, 0, 0, 0, 0]
    fidelity: [0, 0, 0, 0, 0, 0, 0, 0]
    final_delay: [180, 180, 180, 180, 180, 180, 180, 180]
    frequency: [6034.848, 6374.5873, 6727.7834, 6946.6312, 7046.0775, 7583.1666, 7583.1685,
      6999.0182]
    gain: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    kappa: [0.0066, 0.0148, 0.0079, 0.0316, 0.0113, 0.012, 0.0136, 6.4358]
    lamb: [0, 0, 0, 0, 0, 0, 0, 0]
    max_gain: 1
    phase: [0, 0, 0, 0, 0, 0, 0, 0]
    qe: [279.7428, 567.0549, 610.3384, 713.834, 350.563, 1051.553, 1040.9319, 4.6466]
    qi: [137.0802, 46.6334, 98.3562, 22.6818, 76.0308, 67.1771, 59.1135, 0.1114]
    readout_length: [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    reps: [1, 1, 1, 1, 1, 1, 1, 1]
    reps_base: 150
    reset_e: [0, 0, 0, 0, 0, 0, 0, 0]
    reset_g: [0, 0, 0, 0, 0, 0, 0, 0]
    sigma: [0, 0, 0, 0, 0, 0, 0, 0]
    soft_avgs: [1, 1, 1, 1, 1, 1, 1, 1]
    soft_avgs_base: 1
    threshold: [10, 10, 10, 10, 10, 10, 10, 10]
    tm: [0, 0, 0, 0, 0, 0, 0, 0]
    trig_offset: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 0, 0, 0, 0, 0, 0, 0]
    dacs:
      qubit:
        ch: [1, 1, 1, 1, 1, 1, 1, 1]
        nyquist: [1, 1, 1, 1, 1, 1, 1, 1]
        type: [full, full, full, full, full, full, full, full]
      readout:
        ch: [1, 1, 1, 1, 1, 1, 1, 1]
        nyquist: [2, 2, 2, 2, 2, 2, 2, 2]
        type: [full, full, full, full, full, full, full, full]
